name: CI/CD

on:
  push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Activate pnpm
        run: corepack enable

      - name: Instrumentation
        run: |
          pwd
          ls -l
          cat tsconfig.json
          export
          node --version
          pnpm --version

      - name: Install dependencies
        run: pnpm i

      - name: Instrument tsc version
        run: npx tsc --version

      - name: Test
        run: pnpm test

      - name: ESlint
        run: pnpm run lint:check

      - name: Check formatting
        run: pnpm run format:check
